route:
    receiver: 'calert'
    group_wait: 15s
    group_interval: 30s
    repeat_interval: 1m
    group_by: ['room']

receivers:
    - name: 'calert'
      webhook_configs:
      - url: 'http://calert:6000/dispatch'
