[app]
template_file = "/etc/calert/message.tmpl"
max_size = 4000
address = "0.0.0.0:6000"
server_timeout = "5s"
enable_request_logs = true
log = "debug"

[providers.prod_alerts]
endpoint = "https://chat.googleapis.com/v1/spaces/xxx/messages?key=key&token=token%3D"
type = "google_chat"
max_idle_conns =  50
timeout = "7s"
# proxy_url = "http://internal-squid-proxy.com:3128"
template = "static/message.tmpl"
active_alerts_ttl = "12h"

[providers.dev_alerts]
endpoint = "https://chat.googleapis.com/v1/spaces/xxx/messages?key=key&token=token%3D"
type = "google_chat"
max_idle_conns =  50
timeout = "7s"
# proxy_url = "http://internal-squid-proxy.com:3128"
template = "static/message.tmpl"
active_alerts_ttl = "12h"
